#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
        configure)
        if [ -f "/etc/systemd/system/mariadb.service.d/centreon.conf" ]; then
                systemctl daemon-reload
        fi
        if [ -f "/etc/mysql/conf.d/centreon.cnf" ]; then
                systemctl restart mysql
        fi
         ln -s /run/mysqld/mysqld.sock /var/lib/mysql/mysql.sock

        ;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)
        echo "$0: called with unknown argument" 1>&2
        exit 0
        ;;
esac

exit 0	 

