#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
	configure)

    	if [ -f "/lib/systemd/system/cbd.service" ]; then
        	systemctl daemon-reload
        	systemctl enable cbd.service
    	fi

    	if [ -d "/etc/centreon-broker" ]; then
        	chmod 664 /etc/centreon-broker/*
    	fi


    	;;
	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

	*)
    	echo "$0: called with unknown argument" 1>&2
    	exit 0
    	;;
esac

exit 0
