#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
	remove|upgrade|deconfigure)
    	if [ -f "/lib/systemd/system/cbd.service" ]; then
        	systemctl disable cbd.service
        	systemctl daemon-reload
    	fi

    	;;

	failed-upgrade)
    	;;

	*)
    	echo "$0: called with unknown argument" 1>&2
    	exit 0
    	;;
esac

exit 0
