#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
    configure)

    	#test /var/lib/centreon-engine/rw
    	if [ ! -d "/var/lib/centreon-engine/rw" ]; then
        	mkdir -p /var/lib/centreon-engine/rw
    	fi

	;;

    abort-upgrade|abort-remove|abort-deconfigure)
	;;

    *)
	echo "$0: called with unknown argument" 1>&2
	exit 0
	;;
esac

exit 0
